In [2]:
import matplotlib.pyplot as plt 

%matplotlib inline

## DGL Graph Construction

source node와 destination node를 지정하고 노드의 수를 지정함으로써 그래프를 만들 수 있습니다.

이때 source node는 출발 노드를 의미하고 destination 노드는 도착 노드를 의미합니다.

In [3]:
import dgl 
import numpy as np 
import torch 

g = dgl.graph(
    ([0, 0, 0, 0, 0], 
     [1, 2, 3, 4, 5]), num_nodes = 6)

g = dgl.graph(
    (torch.LongTensor([0, 0, 0, 0, 0]), 
     torch.LongTensor([1, 2, 3, 4, 5])), num_nodes = 6
)

g = dgl.graph(
    ([0, 0, 0, 0, 0], 
     [1, 2, 3, 4, 5])
)

print(g)
print(g.edges())

Graph(num_nodes=6, num_edges=5,
      ndata_schemes={}
      edata_schemes={})
(tensor([0, 0, 0, 0, 0]), tensor([1, 2, 3, 4, 5]))


## Assigning Node and Edge Features to Graph 

실제 그래프 내 node와 edge에는 많은 속성들이 존재할 수 있으나, `DGLgraph`는  Tensor 내에 속한 속성들만 고려합니다. 모든 속성들은 node와 edge에 대해서 반드시 동일한 shape를 가지고 있어야 합니다. 

In [4]:
# ndata : node data 
# edata : edge data

g.ndata['x'] = torch.randn(6, 3)
g.edata['a'] = torch.randn(5, 4)
g.ndata['y'] = torch.randn(6, 5, 4)

print(g.edata['a'])

tensor([[ 1.3593, -0.4375,  0.5276,  0.1857],
        [-1.0860, -0.6479,  0.2746,  0.1281],
        [-0.1216,  0.5021,  0.6441,  0.8764],
        [-0.2157, -0.8268,  0.1002,  0.7997],
        [ 2.2535,  1.3702, -0.0113, -0.8284]])


## Querying Graph Structure 

`DGLGraph`는 그래프 구조를 조회하기 위한 다양한 메소드를 제공합니다. 

In [5]:
print(g.num_nodes())
print(g.num_edges())

print(g.out_degrees())
print(g.in_degrees())

6
5
tensor([5, 0, 0, 0, 0, 0])
tensor([0, 1, 1, 1, 1, 1])


## Graph Transformations

In [8]:
# node0, 1, 3으로 구성된 subgraph를 의미합니다.
subgraph1 = g.subgraph([0, 1, 3])

# edge0, 1, 3으로 구성된 subgraph를 의미합니다. 
subgraph2 = g.edge_subgraph([0, 1, 3])

In [12]:
# 새로 생성된 그래프에서 `dgl.NID`, `dgl.EID`를 사용함으로써 subgraph에서 original Graph의 node, edge를 찾을 수 있습니다.

print('original ID of each node in subgraph1', subgraph1.ndata[dgl.NID])
print('original ID of each edge in subgraph1', subgraph1.edata[dgl.EID], '\n')

print('original ID of each node in subgraph2', subgraph2.ndata[dgl.NID])
print('original ID of each edge in subgraph2', subgraph2.edata[dgl.EID])

original ID of each node in subgraph1 tensor([0, 1, 3])
original ID of each edge in subgraph1 tensor([0, 2]) 

original ID of each node in subgraph2 tensor([0, 1, 2, 4])
original ID of each edge in subgraph2 tensor([0, 1, 3])


In [13]:
# subgraph와 edge_subgraph는 node와 edge 뿐만 아니라 feature 까지 가지고 옵니다. 
print(subgraph1.ndata['x'])
print(subgraph1.edata['a'])

print(subgraph2.ndata['x'])
print(subgraph2.edata['a'])

tensor([[ 0.4079, -1.5587, -0.0272],
        [ 0.3309, -0.7207, -2.6636],
        [-1.1461, -1.6150,  0.0752]])
tensor([[ 1.3593, -0.4375,  0.5276,  0.1857],
        [-0.1216,  0.5021,  0.6441,  0.8764]])
tensor([[ 0.4079, -1.5587, -0.0272],
        [ 0.3309, -0.7207, -2.6636],
        [-1.5584, -1.4018,  0.0499],
        [-0.0405, -0.3424,  0.4922]])
tensor([[ 1.3593, -0.4375,  0.5276,  0.1857],
        [-1.0860, -0.6479,  0.2746,  0.1281],
        [-0.2157, -0.8268,  0.1002,  0.7997]])


In [17]:
# add_reverse_edge를 수행하면 undirected graph가 있을 때 이를 양방향 그래프로 변환한 후 실험을 진행하면 보다 좋습니다. 
new_graph = dgl.add_reverse_edges(g)
new_graph.edges()

(tensor([0, 0, 0, 0, 0, 1, 2, 3, 4, 5]),
 tensor([1, 2, 3, 4, 5, 0, 0, 0, 0, 0]))

## Loading and Saving Graphs 

In [ ]:
# glist, label_dict = load_graphs('path')

# Save Graph 
dgl.save_graphs('graph.dgl', g)
dgl.save_graphs('graphs.dgl', [g, subgraph1, subgraph2])

# Load Graph 
(g,), _ = dgl.load_graphs('graph.dgl')
print(g)

(g, subgraph1, subgraph2), _ = dgl.load_graphs('graphs.dgl')
print(g)
print(subgraph1)
print(subgraph2)